version: '2'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=remo
      - POSTGRES_USER=remo
      - POSTGRES_PASSWORD=remo
  memcached:
    image: memcached
  broker:
    image: redis:3
  celery:
    build:
      context: .
      dockerfile: docker/dev
    volumes:
      - .:/app
    links:
      - db
      - broker
      - memcached
    command: ./bin/run-celery.sh
    depends_on:
      - broker
      - db
    environment:
      - C_FORCE_ROOT=True
  web:
    build:
      context: .
      dockerfile: docker/dev
    depends_on:
      - db
      - memcached
      - celery
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db
      - broker
      - celery
      - memcached
    command: ./bin/run-dev.sh
